id: WARM_HILLS
type: BIOME
extends: [ COLOR_XERIC, SAVANNA ]
color: $biomes/colors.yml:WARM_HILLS

features:
  flora:
    - GRASS
    - POPPY_PATCH
    - DANDELION_PATCH
  trees: []

colors:
  grass: 0xc6d563