stages:
  - type: REPLACE_LIST
    default-from: coast-hills
    default-to:
      - coast-hills: 2
      - coast-flat: 1
    to:
      coast-mountains-small:
        - coast-mountains-small: 3
        - coast-hills: 1
        - coast-flat: 3
      coast-mountains-large:
        - coast-mountains-large: 3
        - coast-hills: 1
        - coast-flat: 3
    sampler:
      type: OPEN_SIMPLEX_2
      frequency: 0.1 / ${meta.yml:biome-distribution.global-scale}
      salt: 9129
