id: RIVER_DRIPSTONE
type: BIOME
abstract: true

features:
  river-decoration:
    - MOUNTAIN_RIVER_DRIPSTONE_DEPOSITS
    - MOUNTAIN_RIVER_POINTED_DRIPSTONE
    - LARGE_CEILING_VINES
    - MOUNTAIN_RIVER_GLOW_LICHEN
  ores:
    - CLAY_DEPOSITS