id: GRASS_MOSSY
type: PALETTE

layers:
  - materials:
      - minecraft:grass_block: 20
      - minecraft:moss_block: 4
    layers: 1
  - materials:
      - minecraft:dirt: 2
    layers: 1
  - materials:
      - minecraft:stone: 1
    layers: 1