id: BAMBOO_PONDS_WATER
type: PALETTE

layers:
  - materials:
      - minecraft:water: 1
    layers: 1
  - materials:
      - minecraft:water: 1
      - minecraft:dirt: 1
    layers: 1
  - materials:
      - minecraft:dirt: 1
    layers: 2
  - materials:
      - minecraft:stone: 1
    layers: 1

sampler:
  dimensions: 2
  type: FBM
  octaves: 3
  sampler:
    type: OPEN_SIMPLEX_2
    frequency: 0.05