id: EVERGREEN_FOREST_HILLS
type: BIOME
extends: [ EQ_HILLS, CARVING_LAND, BASE ]
vanilla: minecraft:taiga # This is only so foxes will spawn
color: $biomes/colors.yml:EVERGREEN_FOREST_HILLS

tags:
  - USE_RIVER

colors:
  grass: 0x60bf4b
  foliage: 0x80c465
  water: 0x0677ce
  water-fog: 0x0677ce

palette:
  - GRASS_MOSSY: 319
  - SAND: 64
  - << meta.yml:palette-bottom

slant:
  - threshold: 3
    palette:
      - BLOCK:minecraft:stone: 319
      - << meta.yml:palette-bottom

features:
  flora:
    - GRASS
    - POPPY_PATCH
    - DANDELION_PATCH
    - ROSE_BUSH_PATCH
    - PEONY_PATCH
    - LILAC_PATCH
    - LILY_OF_THE_VALLEY_PATCH
    - FERNS
    - BEETROOT_PATCHES
  trees:
    - SUBTROPICAL_BUSHES
    - EVERGREEN_TREES
  landforms:
    - MOSSY_BOULDERS
    - SMALL_BOULDER_PATCHES
