id: BAMBOO_JUNGLE_FLATS
type: BIOME
extends: [ EQ_PLAIN_PEAKS, JUNGLE ]
color: $biomes/colors.yml:BAMBOO_JUNGLE_FLATS

palette:
  - GRASS: 319
  - GRASS_PODZOL: 62
  - SAND: 61
  - << meta.yml:palette-bottom

tags:
  - USE_RIVER_FLAT_SWAMP

features:
  trees:
    - JUNGLE_TREES
    - JUNGLE_BUSHES
    - POTATO_PATCHES
    - BAMBOO_PATCHES