id: SANDY_BEACH
type: PALETTE

layers:
  - materials:
      - minecraft:sand: 1
    layers: 3
  - materials:
      - minecraft:sand: 8
      - minecraft:clay: 2
      - minecraft:dirt: 3
    layers: 4
  - materials:
      - minecraft:stone: 1
    layers: 1