id: AUTUMNAL_FOREST_HILLS
type: BIOME
extends: [ EQ_HILLS, CARVING_LAND, BASE ]
vanilla: minecraft:birch_forest
color: $biomes/colors.yml:AUTUMNAL_FOREST_HILLS

tags:
  - USE_RIVER

colors:
  grass: 0xb5b065
  foliage: 0xffa500
  water: 0x1e97f2
  water-fog: 0x1e97f2

palette:
  - GRASS: 319
  - SAND: 64
  - << meta.yml:palette-bottom

slant:
  - threshold: 3
    palette:
      - GRANITE_SLANT: 319
      - << meta.yml:palette-bottom

features:
  flora:
    - GRASS
    - POPPY_PATCH
    - DANDELION_PATCH
    - ROSE_BUSH_PATCH
    - PEONY_PATCH
    - LILAC_PATCH
    - LILY_OF_THE_VALLEY_PATCH
    - PUMPKIN_PATCHES
  trees:
    - SEASONAL_TREES
