id: EVERGREEN_TREES
type: FEATURE

distributor:
  type: PADDED_GRID
  width: 6
  padding: 2
  salt: 8491

locator:
  type: AND
  locators:
    - type: TOP
      range: &range
        min: 64
        max: 255
    - type: PATTERN
      range: *range
      pattern:
        type: MATCH_SET
        blocks: $features/vegetation/meta.yml:plantable-blocks
        offset: -1
    - type: PATTERN
      range: *range
      pattern:
        type: MATCH_SET
        blocks:
          - minecraft:snow
          - minecraft:air
        offset: 0

structures:
  distribution:
    type: CELLULAR
    return: CellValue
    frequency: 0.02
  structures:
    - blank: 12
    - oak_tree_procedural: 7
    - large_oak_tree_procedural: 0.025
    - large_oak_tree_procedural_2: 0.025
    - spruce_tree_procedural: 8