id: AMETHYST_GEODES
type: FEATURE

distributor:
  type: AND
  distributors:
    - type: PADDED_GRID
      width: 30
      padding: 5
      salt: 2274
    - type: SAMPLER
      sampler:
        type: PROBABILITY
        sampler:
          type: OPEN_SIMPLEX_2
          salt: 9333
          frequency: 0.0416667
      threshold: 1

locator:
  type: RANDOM
  height:
    min: -42
    max: 30
  amount: 1
  salt: 7414

structures:
  distribution:
    type: CONSTANT
  structures: amethyst_geode
